language: csharp
solution: TodoList.sln
mono: none
dotnet: 2.1.402
script:
 - dotnet restore TodoList.Web/TodoList.Web.csproj
 - dotnet build TodoList.Web/TodoList.Web.csproj
 - dotnet test TodoList.UnitTests/
