version: "3"
services:
    web:
        build: .
        enviroment:
            - ASPNETCORE_ENVIRONMENT=Production
        ports:
            - "8081:80"
        depends_on:
            - db
    db:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Password#"
            ACCEPT_EULA: "Y"
