name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      env:
         GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        repo-token: ${{ GITHUB_TOKEN }}
        pr-message: 'Thank you for contributing to this OS project. We will review your forst PR as soon as possible🎉🎉'' first pr'
